[platformio]
default_envs = nosecone

[env:nosecone]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8
    adafruit/Adafruit ICM20X@^2.0.6
    adafruit/Adafruit BMP3XX Library@^2.1.5
    adafruit/Adafruit Unified Sensor@^1.1.15
    https://github.com/sandeepmistry/arduino-LoRa.git

build_flags =
    -I include