[platformio]
default_envs = nosecone

[env:nosecone]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3 @ ^3.0.6
    sandeepmistry/LoRa
    adafruit/Adafruit LSM6DS
    mikalhart/TinyGPSPlus
    https://github.com/adafruit/Adafruit_Sensor.git
    adafruit/Adafruit BusIO @ ^1.16.1
    robtillaart/MS5611_SPI
    adafruit/Adafruit Unified Sensor@^1.1.15
    https://github.com/sandeepmistry/arduino-LoRa.git
    jgromes/RadioLib@^7.3.0

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1