[platformio]
default_envs = nosecone

[env:nosecone]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8
    sandeepmistry/LoRa
    adafruit/Adafruit LSM6DS
    mikalhart/TinyGPSPlus
    robtillaart/MS5611_SPI
    adafruit/Adafruit Unified Sensor@^1.1.15
    https://github.com/sandeepmistry/arduino-LoRa.git

build_flags =
    -I include