{
 "title": "EGSE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Fill",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt5\")\n  |> yield(name: \"pt5\")\n\n"
    }
   ]
  },
  {
   "title": "Fill",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt5\")\n  |> yield(name: \"pt5\")\n\n"
    }
   ]
  },
  { "title": "Tank", "type": "library-panel-ref", "gridPos": { "h": 15, "w": 6, "x": 12, "y": 0 } },
  { "title": "Tank", "type": "library-panel-ref", "gridPos": { "h": 15, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Bottle",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt4\")\n  |> yield(name: \"pt4\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt4\")\n  |> yield(name: \"pt4\")\n\n"
    }
   ]
  },
  {
   "title": "Pneumatics",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  },
  {
   "title": "Pneumatics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  }
 ]
}