{
 "title": "Radio",
 "time": { "from": "2026-05-15T01:17:13.413Z", "to": "2026-05-15T01:19:13.413Z" },
 "refresh": "1s",
 "panels": [
  {
   "title": "baro_alt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"baro_alt\")\n  |> yield(name: \"baro_alt\")\n\n"
    }
   ]
  },
  {
   "title": "gps_fix",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"gps_fix\")\n  |> yield(name: \"gps_fix\")\n\n"
    }
   ]
  },
  {
   "title": "lat",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"lat\")\n  |> yield(name: \"lat\")\n\n"
    }
   ]
  },
  { "title": "Chamber", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 } },
  { "title": "Chamber", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 5, "x": 4, "y": 9 } },
  {
   "title": "az",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"az\")\n  |> yield(name: \"az\")\n\n"
    }
   ]
  },
  {
   "title": "gz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"gz\")\n  |> yield(name: \"gz\")\n\n"
    }
   ]
  },
  {
   "title": "lon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"lon\")\n  |> yield(name: \"lon\")\n\n"
    }
   ]
  },
  { "title": "Tank", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 } },
  { "title": "Tank", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 5, "x": 4, "y": 16 } },
  {
   "title": "ax",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"ax\")\n  |> yield(name: \"ax\")\n\n"
    }
   ]
  },
  {
   "title": "ay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"ay\")\n  |> yield(name: \"ay\")\n\n"
    }
   ]
  },
  {
   "title": "gx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"gx\")\n  |> yield(name: \"gx\")\n\n"
    }
   ]
  },
  {
   "title": "gy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nosecone_data\")\n  |> filter(fn: (r) => r._field == \"gy\")\n  |> yield(name: \"gy\")\n\n"
    }
   ]
  },
  { "title": "Manifold", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 } },
  { "title": "Manifold", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 5, "x": 4, "y": 22 } }
 ]
}