listener 1883

allow_anonymous true

# Logging:
log_dest stdout
log_type all
connection_messages true

# Running this with
# mosquitto -c mosquitto2.conf -v
# Will begin logging all connections and sends happening to this mqtt server
# Ending/Closing the terminal process WILL END THE SERVER
# IF YOU CLOSE THE TERMINAL YOU NEED TO RERUN IT!!!!!!!
