{
 "title": "So",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "title": "Pneumatics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  },
  {
   "title": "Pneumatics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  },
  {
   "title": "Fill",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt2\")\n  |> yield(name: \"pt2\")\n\n"
    }
   ]
  },
  {
   "title": "Fill",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt2\")\n  |> yield(name: \"pt2\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt1\")\n  |> yield(name: \"pt1\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Abdel Boshara\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt1\")\n  |> yield(name: \"pt1\")\n\n"
    }
   ]
  }
 ]
}