; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; other boards
[env:upesy_wroom]
build_src_filter = +<main.cpp> +<ADS8688.cpp>
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino


;normal
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I ${PROJECT_DIR}

; [env:esp32wroom]
; platform = espressif32
; board = esp32dev
; framework = arduino
; upload_port = /dev/cu.usbserial-0001
; monitor_port = /dev/cu.usbserial-0001

;build_unflags =
;    -D ARDUINO_USB_MODE

monitor_speed = 115200
upload_speed = 921600
board_upload.wait_for_upload_port = yes
;board_upload.use_1200bps_touch = yes
board_upload.resetmethod = default_reset
lib_deps =
    knolleary/PubSubClient
    adafruit/Adafruit ADS1X15
    adafruit/Adafruit BusIO
