{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Fill",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt5\")\n  |> yield(name: \"pt5\")\n\n"
    }
   ]
  },
  {
   "title": "Fill",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt5\")\n  |> yield(name: \"pt5\")\n\n"
    }
   ]
  },
  {
   "title": "Tank",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt2\")\n  |> yield(name: \"pt2\")\n\n"
    }
   ]
  },
  {
   "title": "Tank",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt2\")\n  |> yield(name: \"pt2\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt4\")\n  |> yield(name: \"pt4\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt4\")\n  |> yield(name: \"pt4\")\n\n"
    }
   ]
  },
  {
   "title": "Thrust LC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"lc0\")\n  |> yield(name: \"lc0\")\n\n"
    }
   ]
  },
  {
   "title": "Thrust LC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"lc0\")\n  |> yield(name: \"lc0\")\n\n"
    }
   ]
  },
  {
   "title": "Chamber",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt1\")\n  |> yield(name: \"pt1\")\n\n"
    }
   ]
  },
  {
   "title": "Pneumatics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  },
  {
   "title": "Tank LC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"lc1\")\n  |> yield(name: \"lc1\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt0\")\n  |> yield(name: \"pt0\")\n\n"
    }
   ]
  },
  {
   "title": "Chamber",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt1\")\n  |> yield(name: \"pt1\")\n\n"
    }
   ]
  },
  {
   "title": "Pneumatics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt3\")\n  |> yield(name: \"pt3\")\n\n"
    }
   ]
  },
  {
   "title": "Tank LC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"lc1\")\n  |> yield(name: \"lc1\")\n\n"
    }
   ]
  },
  {
   "title": "Bottle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"rocket_data\")\n  |> filter(fn: (r) => r._field == \"pt0\")\n  |> yield(name: \"pt0\")\n\n"
    }
   ]
  }
 ]
}